/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Napakalaki.CombatResult;
import Napakalaki.Napakalaki;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Marcos
 */
public class NapakalakiView extends javax.swing.JFrame {

    Napakalaki napakalakiModel;
    CombatResult combate;
    /**
     * Creates new form NapakakiView
     */
    public NapakalakiView() {
        initComponents();
        this.monsterView2.setVisible(false);
        this.jButton2.setEnabled(false);
        this.jButton3.setEnabled(false);
        ((JPanel)getContentPane()).setOpaque(false); 
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/fondo.jpg"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER); 
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        this.jLabel1.setVisible(false);
        this.resultadoCombate.setVisible(false);
        
    }
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel=n;
        PlayerView.setNapakalaki(n);
        this.monsterView2.setMonster(n.getCurrentMonster());
        this.playerView2.setPlayer(n.getCurrentPlayer());
        repaint();
        revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resultadoCombate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        playerView2 = new GUI.PlayerView();
        jLabel1 = new javax.swing.JLabel();
        monsterView2 = new GUI.MonsterView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resultadoCombate.setForeground(new java.awt.Color(255, 0, 51));
        resultadoCombate.setText("jLabel1");

        jButton1.setText("Meet the Monster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Combat");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Next turn");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Resultado del Combate:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(resultadoCombate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(playerView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monsterView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resultadoCombate)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        combate=napakalakiModel.developCombat();//napakalakiModel.getCurrentPlayer().combat(napakalakiModel.getCurrentMonster());
        if(combate==CombatResult.LOSE || combate==CombatResult.LOSEANDCONVERT){
            playerView2.setBadConsequence(napakalakiModel.getCurrentMonster().getBadConsequence());
        }
        this.resultadoCombate.setText(combate.toString());
        //napakalakiModel.developCombat();
        this.playerView2.activarBoton();
        this.jButton2.setEnabled(false);
        this.jLabel1.setVisible(true);
        this.resultadoCombate.setVisible(true);
        this.setNapakalaki(napakalakiModel);
        repaint();
        revalidate();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.monsterView2.setVisible(true);
        this.playerView2.desactivarBoton();
        this.jButton2.setEnabled(true);
        this.jButton3.setEnabled(true);
        this.jButton1.setEnabled(false);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.resultadoCombate.setVisible(false);
        this.jLabel1.setVisible(false);
        boolean ok=napakalakiModel.nextTurn();
        if(ok==false){
            JOptionPane.showMessageDialog(null, "Te falta mal rollo por cumplir o tienes mas de 4 tesoros ocultos. \n (Recuerda que si un mounstro te causa muerte, tienes"
                    + " que descartar todos tus tesoros).");
        }
        else{
            this.jButton1.setEnabled(true);
            this.monsterView2.setVisible(false);
            this.jButton3.setEnabled(false);
            this.playerView2.activarBoton2();
            this.playerView2.setPlayer(napakalakiModel.getCurrentPlayer());
            setNapakalaki(napakalakiModel);
            repaint();
            revalidate();
        }
        
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private GUI.MonsterView monsterView2;
    private GUI.PlayerView playerView2;
    private javax.swing.JLabel resultadoCombate;
    // End of variables declaration//GEN-END:variables
}
